# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

apiVersion: awsblueprints.io/v1alpha1
kind: ObjectStorage
metadata:
  name: cp-front-test-xbucket
  namespace: default
spec:
  compositionSelector:
    matchLabels:
      awsblueprints.io/provider: aws
      awsblueprints.io/environment: dev
      s3.awsblueprints.io/configuration: standard
  writeConnectionSecretToRef:
    name: cp-front-test-xbucket-infos
  resourceConfig:
    providerConfigName: aws-provider-config
    region: eu-west-1
    tags:
      - key: env
        value: dev
