---
apiVersion: v1
kind: Secret
metadata:
  name: ack-test-db-password
  namespace: default
type: Opaque
data:
  password: UDRzc3cwcmQ= # P4ssw0rd
---
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: "ack-test-db"
spec:
  allocatedStorage: 20
  dbInstanceClass: db.t4g.micro
  dbInstanceIdentifier: "ack-test-db"
  engine: mariadb
  engineVersion: "10.6"
  masterUsername: "admin"
  masterUserPassword:
    namespace: default
    name: "ack-test-db-password"
    key: password
