apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: cp-ack-test-pkg
spec:
  crossplane:
    version: ">=v1.10.1"
  dependsOn:
    - configuration: xpkg.upbound.io/upbound/platform-ref-aws
      version: ">=v0.4.1"
    - configuration: xpkg.upbound.io/upbound/platform-ref-gcp
      version: ">=v0.3.0"
